.TH "lib/Zany/Context.hpp" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Zany/Context.hpp \- Execution queue of the tasks\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <queue>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <condition_variable>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'Context\&.ipp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBzany::InterfaceContext\fP"
.br
.ti -1c
.RI "class \fBzany::Context\fP"
.br
.RI "One implementation of context\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzany\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Execution queue of the tasks\&. 


.PP
\fBAuthor:\fP
.RS 4
Benjamin Viguier 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
