.TH "lib/Zany/Pipeline.hpp" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Zany/Pipeline.hpp \- Execution queue of the tasks\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <array>\fP
.br
\fC#include '\&./Property\&.hpp'\fP
.br
\fC#include '\&./ThreadPool\&.hpp'\fP
.br
\fC#include '\&./HttpRequest\&.hpp'\fP
.br
\fC#include 'Pipeline\&.ipp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBzany::Pipeline\fP"
.br
.ti -1c
.RI "class \fBzany::Pipeline::Hooks\fP"
.br
.ti -1c
.RI "class \fBzany::Pipeline::Set\fP"
.br
.ti -1c
.RI "class \fBzany::Pipeline::Instance\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzany\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Execution queue of the tasks\&. 


.PP
\fBAuthor:\fP
.RS 4
Benjamin Viguier 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
