.TH "zany::Loader::AbstractModule::Collector" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::Loader::AbstractModule::Collector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPipeline::Set::ID\fP \fBoperator<<\fP (\fBPipeline::Set::ID\fP id)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
