.TH "zany::evt::Event::EvtHdlBlock< Ret, Args >" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::evt::Event::EvtHdlBlock< Ret, Args >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBzany::evt::Event::EvtHdlBlockDestr\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::function< Ret(Args\&.\&.\&.)> \fBhdl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
