.TH "zany::evt::EventWrapper" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::evt::EventWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventWrapper\fP (\fBEvent\fP &evt, std::function< void(void)> const &hdl)"
.br
.ti -1c
.RI "\fBEvent\fP * \fBoperator\->\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
