.TH "zany::evt::BasicManager< T >" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::evt::BasicManager< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventWrapper\fP \fBoperator[]\fP (T const &eventName)"
.br
.ti -1c
.RI "void \fBremoveEvent\fP (T const &eventName)"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBBasicManager\fP & \fBget\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
