.TH "zany::evt::Event::FctSign< T >" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::evt::Event::FctSign< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = T"
.br
.ti -1c
.RI "using \fBret\fP = std::shared_ptr< std::vector< T > >"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
