.TH "zany::evt::HdlCollector" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::evt::HdlCollector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Event::EvtHdlDestr \fBadd\fP (Event::EvtHdlDestr const &)"
.br
.ti -1c
.RI "\fBHdlCollector\fP & \fBoperator<<\fP (Event::EvtHdlDestr const &)"
.br
.ti -1c
.RI "void \fBflush\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
