.TH "zany::HttpResponse" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::HttpResponse
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBzany::HttpBaseRequest\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
