.TH "zany::Pipeline::Set::ID" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::Pipeline::Set::ID
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSet\fP * \fBset\fP"
.br
.ti -1c
.RI "std::uint16_t \fBPRSignValue\fP"
.br
.ti -1c
.RI "std::uint64_t \fBuniqueId\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
