.TH "zany::Pipeline::Set::_FunctionTypeSelector< Pipeline::Rights::READ_ONLY >" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::Pipeline::Set::_FunctionTypeSelector< Pipeline::Rights::READ_ONLY >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = std::function< void(\fBPipeline::Instance\fP const &)>"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
