.TH "zany::HttpHeader" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::HttpHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHttpHeader\fP (std::string const &data)"
.br
.ti -1c
.RI "bool \fBisNumber\fP ()"
.br
.ti -1c
.RI "double \fBgetNumber\fP ()"
.br
.ti -1c
.RI "std::string const  & \fBgetData\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
