.TH "zany::HttpBaseRequest" 3 "Tue Feb 12 2019" "Zia API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zany::HttpBaseRequest
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBzany::HttpRequest\fP, and \fBzany::HttpResponse\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBprotocole\fP"
.br
.ti -1c
.RI "std::string \fBprotocoleVersion\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, \fBHttpHeader\fP > \fBheaders\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia API from the source code\&.
