REDIRECT_STATUS=true
SCRIPT_FILENAME=/home/pc/Delivery/ZIA/assets/PHPForm/verif.php
REQUEST_METHOD=POST
GATEWAY_INTERFACE=CGI/1.1
CONTENT_LENGTH=6

export REDIRECT_STATUS
export SCRIPT_FILENAME
export REQUEST_METHOD
export GATEWAY_INTERFACE
export CONTENT_LENGTH

echo "test=1" | php-cgi